name: telegram_bot_api
description: Telegram Bot API Client.
version: 1.0.0
homepage: https://gitlab.darkwolf.cloud/cyberviking/dart-telegram-bot-api

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
  http_parser: ^4.0.2
  shelf: ^1.4.0
